export const LOADING_TRUE = 'LOADING_TRUE';
export const LOADING_FALSE = 'LOADING_FALSE';


export const GET_TRENDING = 'GET_TRENDING';

export const GET_SINGLE_CINEMA = 'GET_SINGLE_CINEMA';
export const GET_SINGLE_CINEMA_VIDEO = 'GET_SINGLE_CINEMA_VIDEO';
export const GET_SINGLE_CINEMA_CREDITS = 'GET_SINGLE_CINEMA_CREDITS';

export const GET_MOVIES = 'GET_MOVIES';
export const GET_MOVIES_GENRES_DATA = 'GET_MOVIES_GENRES_DATA';
export const SET_MOVIES_SELECTED_GENRES = 'SET_SELECTED_GENRES';


export const GET_SERIES = 'GET_SERIES';
export const GET_SERIES_GENRES_DATA = 'GET_SERIES_GENRES_DATA';
export const SET_SERIES_SELECTED_GENRES = 'SET_SERIES_SELECTED_GENRES';

export const GET_SEARCH_CINEMA_DATA = 'GET_SEARCH_CINEMA_DATA';
export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';